issuer: https://token.actions.githubusercontent.com
subject: "repo:Depthmark/reusable-workflows:ref:refs/heads/main"

claim_pattern:
  workflow_ref: "Depthmark/reusable-workflows/.github/workflows/release-please.yml@refs/heads/main"

permissions:
  contents: write
  checks: write
  pull_requests: write
